// src/constants/mockUsers.ts

export const MOCK_USERS = [
  {
    _id: 'USR001',
    email: 'nguyenvana@gmail.com',
    phoneNumber: '0901234567',
    authProvider: 'LOCAL',
    isProfileCompleted: true,
    role: 'USER',
    fullName: 'Nguyễn Văn A',
    avatar: '',
    defaultAddress: '123 Lê Lợi, Phường Bến Thành, Quận 1, TP.HCM',
    kycStatus: 'VERIFIED',
    kycDocuments: [],
    greenPoints: 120,
    averageRating: 4.8,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-15T08:30:00'),
    updatedAt: new Date('2026-03-20T10:00:00'),
  },
  {
    _id: 'USR002',
    email: 'cuahangb@foodshare.vn',
    phoneNumber: '0987654321',
    authProvider: 'GOOGLE',
    isProfileCompleted: true,
    role: 'STORE',
    fullName: 'Cửa hàng Bánh Mì B',
    avatar: '',
    defaultAddress: '456 Nguyễn Thị Minh Khai, Phường 5, Quận 3, TP.HCM',
    kycStatus: 'PENDING',
    kycDocuments: ['doc1.jpg'],
    storeInfo: {
      openHours: '06:00 - 22:00',
      description: 'Chuyên cung cấp bánh mì thịt nướng và bánh ngọt các loại.',
      businessAddress: '456 Nguyễn Thị Minh Khai, Phường 5, Quận 3, TP.HCM',
    },
    greenPoints: 550,
    averageRating: 5.0,
    status: 'ACTIVE',
    createdAt: new Date('2026-02-10T09:15:00'),
    updatedAt: new Date('2026-03-25T14:20:00'),
  },
  {
    _id: 'USR003',
    email: 'tranthic_spam@yahoo.com',
    phoneNumber: '0911223344',
    authProvider: 'LOCAL',
    isProfileCompleted: false,
    role: 'USER',
    fullName: 'Trần Thị C',
    avatar: '',
    defaultAddress: '789 Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM',
    kycStatus: 'REJECTED',
    kycDocuments: [],
    greenPoints: 0,
    averageRating: 2.1,
    status: 'BANNED',
    createdAt: new Date('2026-03-01T11:00:00'),
    updatedAt: new Date('2026-03-28T09:00:00'),
  },
];
